version: '3'
services:
  kafka:
    container_name: kafka
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/kafka:latest
    external_links:
    - zookeeper
    ports:
    - 9092:9092
    - 8081:8081
    - 8082:8082
    - 8083:8083
    environment:
      AVRO: "false"
networks:
  default:
    external:
      name: parrot_default