version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: parrotstream/zookeeper:latest
    networks:
    - parrot
    ports:
    - '2181:2181'
    - '2888:2888'
    - '3888:3888'
  kafka:
    container_name: kafka
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/kafka:0.10.0.1-3.0.1
    networks:
    - parrot
    links:
    - zookeeper
    ports:
    - 9092:9092
    - 8081:8081
    - 8082:8082
    - 8083:8083
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge
