version: "2"

services:

    zookeeper:
        extends:
            file: zookeeper.yml
            service: zookeeper

    kafka:
        build:
            context: .
            dockerfile: Dockerfile
        image: mcapitanio/kafka:latest
        networks:
            - hadoop
        links:
            - zookeeper
        volumes:
            - kafka_conf:/etc/kafka
            - kafka_logs:/var/log/kafka
            - kafka_rest_conf:/etc/kafka-rest
            - schema_registry_conf:/etc/schema-registry
        ports:
            - "9092:9092"
            - "8081:8081"
            - "8082:8082"
            - "8083:8083"
            - "8000:8000"

volumes:
    kafka_conf:
    kafka_logs:
    kafka_rest_conf:
    schema_registry_conf:
    zookeeper_data:
    zookeeper_logs:
    zookeeper_conf:

networks:
    hadoop:
        driver: bridge
