version: "2"

services:

    zookeeper:
        extends:
            file: zookeeper.yml
            service: zookeeper

    kafka:
        image: mcapitanio/kafka:0.10.0.1
        networks:
            - hadoop
        links:
            - zookeeper
        volumes:
            - kafka_conf:/opt/kafka/config
            - kafka_logs:/opt/kafka/logs
            - kafka_manager_conf:/opt/kafka-manager/conf
            - kafka_manager_logs:/opt/kafka-manager/logs
        ports:
            - "9092:9092"
            - "9000:9000"

volumes:
    kafka_conf:
    kafka_logs:
    kafka_manager_conf:
    kafka_manager_logs:
    zookeeper_data:
    zookeeper_logs:
    zookeeper_conf:

networks:
    hadoop:
        driver: bridge
