version: '3'
services:
  zookeeper:
    image: parrotstream/zookeeper:latest
    networks:
    - parrot
    ports:
    - '2181:2181'
    - '2888:2888'
    - '3888:3888'
  kafka:
    build:
      context: .
      dockerfile: Dockerfile
    image: parrotstream/kafka:latest
    networks:
    - parrot
    links:
    - zookeeper
    ports:
    - 9092:9092
    - 8081:8081
    - 8082:8082
    - 8084:8083
    - 8001:8000
    environment:
    - KAFKA_REST_PROXY_URL=http://localhost:8082
    - PROXY=true
    - PROXY_SKIP_VERIFY=true
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge
